version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  my-api-server:
    build: .
    container_name: my-api-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb










