name: Keploy Cloud Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-cloud-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set executable permission for Keploy CLI
        run: chmod +x keploy_linux_amd64/keploy_linux_amd64

      - name: Start the app in background
        env:
          MONGO_URI: mongodb://localhost:27017/test
          PORT: 3000
          HOST: 0.0.0.0
        run: |
          nohup npm start & 
          sleep 10

      - name: Run Keploy Test Suite
        run: |
          ./keploy_linux_amd64/keploy_linux_amd64 test -c "npm start" --delay 10


